![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [43]:
import numpy as np

np.__version__

my_array = np.array(range(10))

my_array[-1:0:-2]



array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [44]:
my_array[8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [45]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [46]:
my_array4 = np.arange(1, 21).reshape(4,5) 
my_array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [47]:
my_array4.T # Cambiar filas por columnas

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [48]:
my_array4[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [49]:
my_array4[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [50]:
my_array4[:-1, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [51]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

loro = x == 'Loro'

x_filtered = x[loro] # Con mascaras: | ~ & es igual que OR, NOT , AND
x_filtered

array(['Loro', 'Loro'], dtype='<U5')

In [52]:
# loro = np.where(x=='Loro')

# x_filtered = x[loro]
x_filtered = x[np.where(x=='Loro')]

x_filtered



array(['Loro', 'Loro'], dtype='<U5')

In [53]:
np.extract(x=='Loro', x)

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [54]:
import numpy as np

np.arange(0,20).reshape(2, 5, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [55]:
my_array4 = np.arange(1, 21).reshape(4,5)
print(my_array4)

my_array4[::-1, ::-1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [56]:
my_array11 = np.full(10, 0)

print(my_array11.nbytes)

my_array11[3] = 1

# print(np.where(my_array11[3], 0, 1))

print(my_array11)


80
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [57]:
my_array12 = np.arange(10, 50)

my_array12[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [58]:
my_array13 = np.array([1,2,0,0,4,0])

np.where(my_array13 > 0)

(array([0, 1, 4]),)

In [59]:
np.nonzero(my_array13)

(array([0, 1, 4]),)

In [60]:
mask = my_array13 > 0


my_array13[mask]

array([1, 2, 4])

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [61]:
my_array14 = np.random.randint(0, 9, (10, 10))


print(my_array14)
print(my_array14.min())
print(my_array14.max())
print(my_array14.mean())

[[7 6 3 3 3 3 1 7 1 8]
 [8 3 6 0 6 6 0 7 4 8]
 [2 3 6 0 8 0 8 1 1 1]
 [7 1 4 4 1 5 0 5 3 2]
 [5 7 4 4 3 2 3 1 4 7]
 [3 6 7 2 6 6 4 5 8 0]
 [2 1 4 4 5 5 0 6 6 7]
 [1 8 4 3 2 8 7 6 0 8]
 [4 5 5 2 8 3 0 7 6 4]
 [3 8 0 8 4 6 6 4 3 4]]
0
8
4.16


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [62]:
my_array15 = np.arange(0, 30).reshape(3, 2, 5)

print(my_array15.size)

print(my_array15)


30
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [63]:
myarray16 = np.full((2, 5), 1)
myarray16[:, [1, 2, 3]] = 0

print(myarray16)

# print(myarray16.size)
# print(myarray16.shape)
print(myarray16.ndim)



[[1 0 0 0 1]
 [1 0 0 0 1]]
2


In [64]:
myarray16 = np.full((3, 3, 3), 1)

myarray16[[0][0]][0]= 0
myarray16[[2][0]][2]= 0
myarray16[:,:,[0,2]]= 0
myarray16

array([[[0, 0, 0],
        [0, 1, 0],
        [0, 1, 0]],

       [[0, 1, 0],
        [0, 1, 0],
        [0, 1, 0]],

       [[0, 1, 0],
        [0, 1, 0],
        [0, 0, 0]]])

In [65]:
x = np.ones((10, 10))

x[1:-1:, 1:-1:] = 0

print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [66]:
x = np.ones((9,9))
np.pad(x,1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [67]:
myarray17 = np.full((8,8), 0)

myarray17[::2,1::2]=1
myarray17[1::2,::2]=1
print(myarray17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
myarray18 = np.tile((0,1),(8, 4))

myarray18[1::2,::] = myarray18[1::2,::-1] 

myarray18

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [69]:
myarray18 = np.tile(([0,1],[1,0]),(4, 4))
myarray18

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [70]:
array9 = np.random.randint(1, 9, (5, 5))

array9_mean = array9 - np.mean(array9)

array9_std = array9 / np.std(array9)

print(array9)

print(array9_mean)

print(array9_std)

[[8 7 7 8 7]
 [7 4 1 1 7]
 [4 4 1 4 8]
 [6 7 5 3 7]
 [3 2 6 4 8]]
[[ 2.84  1.84  1.84  2.84  1.84]
 [ 1.84 -1.16 -4.16 -4.16  1.84]
 [-1.16 -1.16 -4.16 -1.16  2.84]
 [ 0.84  1.84 -0.16 -2.16  1.84]
 [-2.16 -3.16  0.84 -1.16  2.84]]
[[3.43807082 3.00831197 3.00831197 3.43807082 3.00831197]
 [3.00831197 1.71903541 0.42975885 0.42975885 3.00831197]
 [1.71903541 1.71903541 0.42975885 1.71903541 3.43807082]
 [2.57855312 3.00831197 2.14879426 1.28927656 3.00831197]
 [1.28927656 0.85951771 2.57855312 1.71903541 3.43807082]]


In [71]:
print(np.mean(array9, axis=0))
print(np.mean(array9, axis=1))
print(np.mean(array9, None))

[5.6 4.8 4.  4.  7.4]
[7.4 4.  4.2 5.6 4.6]
5.16


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [72]:
array10 = np.array(range(11))



array10[3:9] = -1


print(array10)

# array10[3:9] = -array10[3:9] 

# print(array10)



[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [73]:
array10 = np.array(range(11))



array10[3:9] = -array10[3:9] 

print(array10)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [74]:
array10 = np.array(range(11))


print(np.where((array10 > 3) & (array10 < 8), -1, array10)) # apartado 2

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [75]:
array10[(array10 > 3) & (array10 < 9)] = -1

array10

array([ 0,  1,  2,  3, -1, -1, -1, -1, -1,  9, 10])

In [76]:
array10 = np.array(range(11))
array10[(array10 > 3) & (array10 < 9)] *= -1

array10

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.